### ISSUE TITLE
Hey Mosh 

### ISSUE THREAD

**Issue by skdrh** [mosh-hamedani/issue-tracker#11]
I learned next.js from this course **Thank you**. What i have learned in this course now I'm able to build and create my own applications, I'm now working on a open source projects inspire by many, one of them is this [project manager](https://github.com/dragon-devs/project-manager) please check it out. and give me your review. I put everything in it what i have learned from you. :) your comment on it will make my day. 👍

**Comment by artistatbl** [comment]
Let's speak about your idea; I'm working on something similar and would want to talk to someone about it.

**Comment by skdrh** [comment]
Sup bro, of course, we can talk about it. I would love to hear it.

**Comment by artistatbl** [comment]
Yeah, thanks. I'm in university right now, finishing up my final year project, and the idea behind my web app is to create an issue logger for organization-type work, where the admin will have all the access they need to invite their employees into the app and log the issues and assign them to a user. Additional features will be added in the future.

**Comment by skdrh** [comment]
the project i'm working on now is a complete thing, i'm still working on it. i will add the options later for selecting options like bugs, tasks, and projects. there will be a complete comments section for each project that we have here in github. today i just updated it and add a the assign user to the project details page and plus added the user profile view. personal view where you can see the assign projects you can change the state of the each project. i'm going to add many more things there like progress option. client, github repo. and many more. i'm looking for a job while practicing here.
