### ISSUE TITLE
Object literal may only specify known properties, and 'assignedToUserId' does not exist in type

### ISSUE THREAD

**Issue by fsdhemanth648** [mosh-hamedani/issue-tracker#3]
const updatedIssue = await prisma.issue.update({
    where: { id: issue.id },
    data: {
      title,
      description,
      assignedToUserId,
    },
  });
  
  Object literal may only specify known properties, and 'assignedToUserId' does not exist in type '(Without<IssueUpdateInput, IssueUncheckedUpdateInput> & IssueUncheckedUpdateInput) | (Without<...> & IssueUpdateInput)'.ts(2353)
index.d.ts(2083, 5): The expected type comes from property 'data' which is declared here on type '{ select?: IssueSelect<DefaultArgs> | null | undefined; data: (Without<IssueUpdateInput, IssueUncheckedUpdateInput> & IssueUncheckedUpdateInput) | (Without<...> & IssueUpdateInput); where: IssueWhereUniqueInput; }'

**Comment by trxtk89** [comment]
Run
`npx prisma generate`
